stages:
  prepare:
    cmd: python src/data/prepare_data.py
    deps:
      - src/data/prepare_data.py
      - src/database/db_connection.py
    outs:
      - data/syndrome_data.db
    metrics:
      - data/metrics.json:
          cache: false

  validate:
    cmd: python src/database/check_db.py
    deps:
      - src/database/check_db.py
      - data/syndrome_data.db
    metrics:
      - logs/validation.json:
          cache: false